sudo: required
dist: trusty
language: node_js

# test with node 4.*, 5.*
node_js:
- "4"
- "5"

# cache node_modules (read more: https://docs.travis-ci.com/user/caching/)
cache:
  directories:
    - node_modules

env:
  CXX=g++-4.8

before_install:
- npm install -g npm@latest

before_script:
# set up UI for travis-ci (read more https://docs.travis-ci.com/user/gui-and-headless-browsers/)
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

# start file server in background
- npm start &
- sleep 3

# up browserstack tunnel
- npm run bstack-tunnel &

script:
- npm run e2e-bstack
